<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MAIN" Id="{527f438a-01c8-4e6e-8aa4-aea9433d8d02}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//LogicTester();
LogicTester2();

// Main Routine
Initialize();
MainCycle();
Counters();
FaultDetection();
HMIUpdates();









]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>